### ISSUE TITLE
No compatible binary build found for this package

### ISSUE THREAD

**Issue by hems** [hitchcott/meteor-embark#1]
I'm getting the following error when trying to run the example project

```
meteor-embark/example [ EMBARK_DEBUG=1 meteor                                                                                                     master ] 5:49 pm
[[[[[ /Volumes/backpack/git/xxx/tests/meteor-embark/example ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for hitchcott:embark@0.6.3:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.
```

```
meteor-embark/example [ meteor --version                                                                                                        master * ] 5:51 pm
Meteor 1.2.1
```

**Comment by bigmoby** [comment]
Same error non Mac OS X.
Meteor 1.2.1
Embark 1.0.2

**Comment by hems** [comment]
@bigmoby i think you have to install geth / ethereum before, and that's all.

**Comment by hems** [comment]
@bigmoby you probably want to use the --with-gui option!

https://github.com/ethereum/webthree-umbrella/wiki/Building-on-OS-X

**Comment by bigmoby** [comment]
@hems Hi, thank You for the reply. Unfortunately I've just geth installed. But...one question... must be geth running before meteor-embark?
Thank You

**Comment by hems** [comment]
@bigmoby i have the impression once you have installed if you run embark everything will be smooth, at least that is how it worked for me.

**Comment by IstoraMandiri** [comment]
Weird, it seemed to be working before, but I've just published using `meteor publish-for-arch hitchcott:embark@0.6.4` for osx.

Perhaps it'll be working for you now?

**Comment by kartojal** [comment]
Same happens on Ubuntu 14.04:

Output of **meteor add hitchcott:embark**:

 => Errors while adding packages:             

While checking for hitchcott:embark@0.6.0:
error: No compatible binary build found for this package. Contact the package author and ask
them to publish it for your platform.

**Comment by IstoraMandiri** [comment]
@kartojal I've published for Ubuntu now. Is that working?

Also I found that embark isn't compatible with `geth 1.4` yet, so make sure you use `geth 1.3.x`

**Comment by mattlinares** [comment]
When running:

`EMBARK_DEBUG=1 meteor publish-for-arch hitchcott:embark@0.6.4`

I'm getting:

`hitchcott:embark  added, version 0.6.4

=> Errors while publishing build:

While creating package build for hitchcott:embark:
error: You are not an authorized maintainer for this package.`


Any ideas? Thanks!

**Comment by IstoraMandiri** [comment]
This project is now deprecated - I won't be updating it anymore. I suggest using truffle or embark proper. 

Sorry!
